name: PHP Code Review
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4 # Replace with the version of PHP you are using
      
      - name: Validate code
        run: php -l Backend/ # Replace with the path to your PHP files
